### ISSUE TITLE
Group affiliations in website template

### ISSUE THREAD

**Issue by Chilipp** [eileen-kuehn/sorse-data-filter#18]
@eileen-kuehn: related to https://github.com/SORSE/sorse.github.io/pull/248, do you have any problems if we group the affiliations in the YAML front-matter? This would make it easier in the PDF generation workflow and it's also easy to implement in the website. Instead of 

```yaml
authors:
    - name: Dr. Jack Brookes
      bio: University Health Network
    - name: Mr. Matthew Warburton
      bio: University Health Network
    - name: Prof. Mark Mon-Williams
      bio: University Health Network
    - name: Dr. Faisal Mushtaq
      bio: University Health Network
``` 
we would then have

```yaml
authors:
    - name: Dr. Jack Brookes
      affiliation: 1
    - name: Mr. Matthew Warburton
      affiliation: 1
    - name: Prof. Mark Mon-Williams
      affiliation: 1
    - name: Dr. Faisal Mushtaq
      affiliation: 1
affiliations:
    - name: University Health Network
      index: 1
```

If you like, I can make a PR to do this. From an OOP perspective you likely don't want the `affiliation` number be a part of the `Person` class because the latter should work stand-alone. But we can avoid this and do everything with Jinja2 in the  [website.md](https://github.com/SORSE/sorse-data-filter/blob/master/templates/website.md) template. I'd just need add a property named `affiliations` to the `Contribution` class, something like

```python
@property
def affiliations(self):
    """Unique affiliations of the contributors"""
    affiliations = []
    for person in self.persons:
         if person.affiliation and person.affiliation not in affiliations:
            affiliations.append(person.affiliation)
    return affiliations
```
