### ISSUE TITLE
fix YAML encoding of &speaker

### ISSUE THREAD

**Issue by Chilipp** [eileen-kuehn/sorse-data-filter#21]
I just realized, 

```yaml
authors:
    - &speaker name:  someone
author: *speaker
```
does not work because `*speaker` renders to `name`. It needs to be 

```yaml
authors:
    - &speaker 
      name:  someone
author: *speaker
```
